server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: psychological-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/psychological?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  security:
    jwt:
      secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
      expiration: 86400000 # 24小时
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 文件上传配置
file:
  upload:
    # 头像保存路径（相对于项目根目录）
    avatar-path: uploads/avatars
    # 允许的文件类型
    allowed-types: image/jpeg,image/png,image/gif
    # 最大文件大小（单位：字节）
    max-size: 5242880  # 5MB

logging:
  level:
    com.work.psychological: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.work.psychological.model.entity 